// ──────────────────────────────────────────────
// interviewSession — Epic 23.4
// Integration layer between Conversation Engine,
// Interview Agent, and Requirements Builder.
//
// This is a stateless service that orchestrates
// the full interview cycle:
//
//   ConversationEngine → InterviewAgent → LLM
//       → parse → memory update → RequirementsBuilder
//
// It holds NO state, NO React hooks, NO storage.
// Memory is returned as a new object — the caller
// is responsible for persisting it.
// ──────────────────────────────────────────────

import type { Orchestrator } from "../../orchestrator";
import type { ChatMessage } from "../gateway";
import type { ConversationMemory } from "../../models/conversationMemory";
import { createEmptyConversationMemory } from "../../models/conversationMemory";
import type {
  InterviewState,
  EngineResult,
  EngineConfig,
  CompletionBreakdown,
  RequirementsBuildResult,
} from "../../orchestrator";
import {
  ConversationEngine,
  buildRequirements,
} from "../../orchestrator";
import { topicQuestion, topicLabel } from "../../orchestrator/interviewTopics";
import type {
  AgentQuestion,
  InterviewAgentConfig,
  InterviewAgentResult,
} from "./interviewAgentTypes";
import type { PlannedQuestion } from "../../orchestrator/interviewPlanner";
import type { FollowUpQuestion } from "../../orchestrator/followUpEngine";
import { InterviewAgent } from "./InterviewAgent";

// ── Types ─────────────────────────────────────

export interface InterviewSessionConfig {
  /** Orchestrator instance for LLM calls */
  orchestrator: Orchestrator;
  /** Optional InterviewAgent config overrides */
  agentConfig?: InterviewAgentConfig;
  /** Optional ConversationEngine config */
  engineConfig?: EngineConfig;
}

export interface InterviewSessionResult {
  /** Whether the interview is complete (no more questions to ask) */
  done: boolean;
  /** The question text generated by the LLM (assistant message) */
  question?: string;
  /** The user's answer text (if just processed) */
  answer?: string;
  /** The topic of the current/next question */
  topic?: string;
  /** Whether the next question is a follow-up */
  isFollowUp: boolean;
  /** Updated conversation memory (always a new object) */
  memory: ConversationMemory;
  /** Current engine state */
  state: InterviewState;
  /** Current requirements build result */
  requirements: RequirementsBuildResult;
  /** Completion breakdown */
  completion: CompletionBreakdown;
  /** Error message if something failed */
  error?: string;
  /** The raw LLM messages sent/received (for debugging) */
  messages?: ChatMessage[];
}

// ── Helpers ───────────────────────────────────

/**
 * Generate a unique ID for messages and questions.
 */
function uid(): string {
  return crypto.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
}

/**
 * Deep-clone a ConversationMemory to avoid mutating the caller's reference.
 */
function cloneMemory(memory: ConversationMemory): ConversationMemory {
  return JSON.parse(JSON.stringify(memory));
}

/**
 * Convert an EngineResult's nextQuestion to an AgentQuestion.
 * This helper properly narrows the union type based on the isFollowUp flag.
 */
function toAgentQuestion(engineResult: EngineResult): AgentQuestion {
  // We know the nextQuestion is not null here (caller checks before calling)
  const q = engineResult.nextQuestion!;
  if (engineResult.isFollowUp) {
    return { type: "follow-up", question: q as FollowUpQuestion };
  }
  return { type: "planned", question: q as PlannedQuestion };
}

/**
 * Build the session result from an engine result + agent result + memory.
 */
function buildResult(
  engineResult: EngineResult,
  memory: ConversationMemory,
  requirements: RequirementsBuildResult,
  agentResult?: InterviewAgentResult,
): InterviewSessionResult {
  const base: InterviewSessionResult = {
    done: engineResult.nextQuestion === null,
    question: agentResult?.answer.content,
    topic: engineResult.nextQuestion?.topic,
    isFollowUp: engineResult.isFollowUp,
    memory,
    state: engineResult.state,
    requirements,
    completion: engineResult.completion,
    messages: agentResult?.messages,
  };

  if (agentResult && !agentResult.success) {
    base.error = agentResult.error;
  }

  return base;
}

// ── Core: process a user answer ───────────────

/**
 * Process a user's answer to the current interview question.
 *
 * Steps:
 * 1. Record the user's answer in memory
 * 2. Update the open InterviewQuestion for this topic with the answer
 * 3. Feed it to the Conversation Engine to get the next planned question
 * 4. If there is a next question, ask it via the Interview Agent (LLM)
 * 5. Record the LLM-generated question in memory
 * 6. Run the Requirements Builder for the latest snapshot
 * 7. Return the result
 *
 * @param memory       - The current conversation memory (will NOT be mutated)
 * @param config       - Session config (orchestrator, agent config, engine config)
 * @param topic        - The topic this answer belongs to
 * @param answer       - The user's answer text
 * @param engineState  - Optional previous engine state to restore (for state persistence across calls)
 * @returns            - The session result with next question (or done)
 */
export async function processUserAnswer(
  memory: ConversationMemory,
  config: InterviewSessionConfig,
  topic: string,
  answer: string,
  engineState?: InterviewState,
): Promise<InterviewSessionResult> {
  // ── Clone memory — never mutate the caller's reference ──
  const mem = cloneMemory(memory);

  // ── Step 1: Record the user's answer in memory ──
  mem.messages.push({
    id: uid(),
    role: "user",
    content: answer,
    createdAt: new Date().toISOString(),
  });

  // ── Step 2: Update the open InterviewQuestion for this topic with the answer ──
  // This ensures buildRequirements() (called inside the engine) sees the answer
  // and doesn't think the topic is still missing.
  mem.questions = mem.questions.map((q) =>
    q.topic === topic && q.answer === ""
      ? { ...q, answer, answeredAt: new Date().toISOString() }
      : q,
  );

  // ── Step 3: Feed to Conversation Engine ──
  const engine = new ConversationEngine(config.engineConfig);

  // Restore previous engine state if provided, so state persists across calls
  if (engineState) {
    engine.restoreState(engineState);
  }

  const engineResult = engine.processAnswer(mem, topic, answer);

  // ── Step 4: If interview is done, run requirements and return ──
  if (!engineResult.nextQuestion) {
    const requirements = buildRequirements(mem);
    return {
      done: true,
      isFollowUp: false,
      memory: mem,
      state: engineResult.state,
      requirements,
      completion: engineResult.completion,
    };
  }

  // ── Step 5: Ask the next question via Interview Agent (LLM) ──
  const agent = new InterviewAgent(config.orchestrator, config.agentConfig);
  const agentResult = await agent.ask(toAgentQuestion(engineResult), mem);

  // ── Step 6: Handle LLM failure ──
  if (!agentResult.success) {
    const requirements = buildRequirements(mem);
    return {
      done: false,
      isFollowUp: engineResult.isFollowUp,
      topic: engineResult.nextQuestion.topic,
      memory: mem,
      state: engineResult.state,
      requirements,
      completion: engineResult.completion,
      error: agentResult.error ?? "LLM call failed",
      messages: agentResult.messages,
    };
  }

  // ── Step 7: Record the LLM-generated question as assistant message ──
  mem.messages.push({
    id: uid(),
    role: "assistant",
    content: agentResult.answer.content,
    createdAt: new Date().toISOString(),
  });

  // ── Step 8: Record the question in the questions list ──
  mem.questions.push({
    id: uid(),
    topic: engineResult.nextQuestion.topic,
    question: agentResult.answer.content,
    answer: "", // will be filled when user answers
    confidence: "low",
    skipped: false,
    createdAt: new Date().toISOString(),
    answeredAt: null,
  });

  // ── Step 9: Run Requirements Builder ──
  const requirements = buildRequirements(mem);

  return buildResult(engineResult, mem, requirements, agentResult);

}

// ── Core: start a new interview ───────────────

/**
 * Start a new interview session.
 *
 * Steps:
 * 1. Create a fresh ConversationMemory if none provided
 * 2. Ask the Conversation Engine for the first question
 * 3. Ask it via the Interview Agent (LLM)
 * 4. Record the LLM-generated question in memory
 * 5. Run the Requirements Builder
 * 6. Return the result
 *
 * @param memory       - Optional existing memory (if omitted, creates empty)
 * @param config       - Session config (orchestrator, agent config, engine config)
 * @param engineState  - Optional previous engine state (ignored for new interviews — always starts fresh)
 * @returns            - The session result with the first question
 */
export async function startNewInterview(
  config: InterviewSessionConfig,
  memory?: ConversationMemory,
  _engineState?: InterviewState,
): Promise<InterviewSessionResult> {
  // ── Step 1: Create fresh memory if needed ──
  const mem = memory ? cloneMemory(memory) : createEmptyConversationMemory();

  // ── Step 2: Ask Conversation Engine for first question ──
  const engine = new ConversationEngine(config.engineConfig);
  const engineResult = engine.startInterview(mem);

  // ── Step 3: If no first question (shouldn't happen, but handle gracefully) ──
  if (!engineResult.nextQuestion) {
    const requirements = buildRequirements(mem);
    return {
      done: true,
      isFollowUp: false,
      memory: mem,
      state: engineResult.state,
      requirements,
      completion: engineResult.completion,
    };
  }

  // ── Step 4: Ask the first question via Interview Agent (LLM) ──
  const agent = new InterviewAgent(config.orchestrator, config.agentConfig);
  const agentResult = await agent.ask(toAgentQuestion(engineResult), mem);

  // ── Step 5: Handle LLM failure ──
  if (!agentResult.success) {
    const requirements = buildRequirements(mem);
    return {
      done: false,
      isFollowUp: false,
      topic: engineResult.nextQuestion.topic,
      memory: mem,
      state: engineResult.state,
      requirements,
      completion: engineResult.completion,
      error: agentResult.error ?? "LLM call failed",
      messages: agentResult.messages,
    };
  }

  // ── Step 6: Record the LLM-generated question as assistant message ──
  mem.messages.push({
    id: uid(),
    role: "assistant",
    content: agentResult.answer.content,
    createdAt: new Date().toISOString(),
  });

  // ── Step 7: Record the question in the questions list ──
  mem.questions.push({
    id: uid(),
    topic: engineResult.nextQuestion.topic,
    question: agentResult.answer.content,
    answer: "",
    confidence: "low",
    skipped: false,
    createdAt: new Date().toISOString(),
    answeredAt: null,
  });

  // ── Step 8: Run Requirements Builder ──
  const requirements = buildRequirements(mem);

  return buildResult(engineResult, mem, requirements, agentResult);
}

// ── Core: process a user answer in demo mode (no LLM) ──

/**
 * Process a user's answer in demo mode.
 *
 * This is a lightweight path that:
 * 1. Records the user's answer in memory
 * 2. Updates the open InterviewQuestion for this topic
 * 3. Runs the Conversation Engine to advance state
 * 4. Records the next question using the provided scripted question text
 * 5. Runs the Requirements Builder
 *
 * No LLM calls, no provider validation, no AI fallback.
 *
 * @param memory       - The current conversation memory
 * @param topic        - The topic this answer belongs to
 * @param answer       - The user's answer text
 * @param engineState  - Optional previous engine state to restore
 * @param nextQuestionText - The scripted next question text (from demo scenario)
 * @returns            - The session result with next question (or done)
 */
export async function processUserAnswerDemo(
  memory: ConversationMemory,
  topic: string,
  answer: string,
  engineState?: InterviewState,
  nextQuestionText?: string,
): Promise<InterviewSessionResult> {
  // ── Clone memory — never mutate the caller's reference ──
  const mem = cloneMemory(memory);

  // ── Step 1: Record the user's answer in memory ──
  mem.messages.push({
    id: uid(),
    role: "user",
    content: answer,
    createdAt: new Date().toISOString(),
  });

  // ── Step 2: Update the open InterviewQuestion for this topic with the answer ──
  mem.questions = mem.questions.map((q) =>
    q.topic === topic && q.answer === ""
      ? { ...q, answer, answeredAt: new Date().toISOString() }
      : q,
  );

  // ── Step 3: Feed to Conversation Engine ──
  const engine = new ConversationEngine();

  // Restore previous engine state if provided
  if (engineState) {
    engine.restoreState(engineState);
  }

  const engineResult = engine.processAnswer(mem, topic, answer);

  // ── Step 4: If interview is done, run requirements and return ──
  if (!engineResult.nextQuestion) {
    const requirements = buildRequirements(mem);
    return {
      done: true,
      isFollowUp: false,
      memory: mem,
      state: engineResult.state,
      requirements,
      completion: engineResult.completion,
    };
  }

  // ── Step 5: Use scripted question text (or fall back to generic topic question) ──
  const questionText = nextQuestionText ?? topicQuestion(engineResult.nextQuestion.topic) ?? `Tell me more about ${topicLabel(engineResult.nextQuestion.topic)}.`;

  // ── Step 6: Record the question as assistant message ──
  mem.messages.push({
    id: uid(),
    role: "assistant",
    content: questionText,
    createdAt: new Date().toISOString(),
  });

  // ── Step 7: Record the question in the questions list ──
  mem.questions.push({
    id: uid(),
    topic: engineResult.nextQuestion.topic,
    question: questionText,
    answer: "",
    confidence: "low",
    skipped: false,
    createdAt: new Date().toISOString(),
    answeredAt: null,
  });

  // ── Step 8: Run Requirements Builder ──
  const requirements = buildRequirements(mem);

  return {
    done: false,
    isFollowUp: engineResult.isFollowUp,
    topic: engineResult.nextQuestion.topic,
    memory: mem,
    state: engineResult.state,
    requirements,
    completion: engineResult.completion,
  };
}

// ── Core: skip the current topic ──────────────

/**
 * Skip the current topic and move to the next question.
 *
 * @param memory       - The current conversation memory
 * @param config       - Session config
 * @param engineState  - Optional previous engine state to restore (for state persistence across calls)
 * @returns            - The session result with the next question
 */
export async function skipTopic(
  memory: ConversationMemory,
  config: InterviewSessionConfig,
  engineState?: InterviewState,
): Promise<InterviewSessionResult> {
  const mem = cloneMemory(memory);

  const engine = new ConversationEngine(config.engineConfig);

  // Restore previous engine state if provided, so state persists across calls
  if (engineState) {
    engine.restoreState(engineState);
  }

  const engineResult = engine.skipTopic(mem);

  if (!engineResult.nextQuestion) {
    const requirements = buildRequirements(mem);
    return {
      done: true,
      isFollowUp: false,
      memory: mem,
      state: engineResult.state,
      requirements,
      completion: engineResult.completion,
    };
  }

  const agent = new InterviewAgent(config.orchestrator, config.agentConfig);
  const agentResult = await agent.ask(toAgentQuestion(engineResult), mem);

  if (!agentResult.success) {
    const requirements = buildRequirements(mem);
    return {
      done: false,
      isFollowUp: false,
      topic: engineResult.nextQuestion.topic,
      memory: mem,
      state: engineResult.state,
      requirements,
      completion: engineResult.completion,
      error: agentResult.error ?? "LLM call failed",
      messages: agentResult.messages,
    };
  }

  mem.messages.push({
    id: uid(),
    role: "assistant",
    content: agentResult.answer.content,
    createdAt: new Date().toISOString(),
  });

  mem.questions.push({
    id: uid(),
    topic: engineResult.nextQuestion.topic,
    question: agentResult.answer.content,
    answer: "",
    confidence: "low",
    skipped: false,
    createdAt: new Date().toISOString(),
    answeredAt: null,
  });

  const requirements = buildRequirements(mem);

  return buildResult(engineResult, mem, requirements, agentResult);
}
